/**
 * functions.ts
 *
 * Created by Min-Kyu Lee on 24-05-2026
 * Copyright © 2026 Min-Kyu Lee. All rights reserved.
 */

import { FunctionSchema } from "./function-schema";

export const createLongQuotesSlidesSchema: FunctionSchema = {
	name: "createLongQuotesSlides",
	description: "Creates long quote slides with title and content slides",
	parameters: {
		longQuoteItems: {
			name: "longQuoteItems",
			type: "object[]",
			optional: true,
			defaultValue: undefined,
			description: "Array of quote items with title, subtitle, and quote text",
			arrayItemSchema: {
				title: { name: "title", type: "string", optional: false },
				subtitle: { name: "subtitle", type: "string", optional: false },
				quote: { name: "quote", type: "string", optional: false },
				splitMode: { name: "splitMode", type: "string", optional: true, defaultValue: "paragraph", description: "How to split the quote into slides" },
				splitMaxChars: { name: "splitMaxChars", type: "number", optional: true, defaultValue: 500, description: "Max characters per slide (char-count mode only)" },
				titleColor: { name: "titleColor", type: "string", optional: true, description: "Per-item title color, e.g. DARK1 (overrides global)" },
				subtitleColor: { name: "subtitleColor", type: "string", optional: true, description: "Per-item subtitle color, e.g. DARK1 (overrides global)" },
				quoteColor: { name: "quoteColor", type: "string", optional: true, description: "Per-item quote color, e.g. DARK1 (overrides global)" },
				addendumColor: { name: "addendumColor", type: "string", optional: true, description: "Per-item addendum color, e.g. DARK1 (overrides global)" },
				titleBold: { name: "titleBold", type: "boolean", optional: true, description: "Bold title (default: true)" },
				subtitleBold: { name: "subtitleBold", type: "boolean", optional: true, description: "Bold subtitle (default: false)" },
				quoteBold: { name: "quoteBold", type: "boolean", optional: true, description: "Bold quote (default: false)" },
				addendumBold: { name: "addendumBold", type: "boolean", optional: true, description: "Bold addendum (default: false)" },
				titleItalic: { name: "titleItalic", type: "boolean", optional: true, description: "Italic title" },
				subtitleItalic: { name: "subtitleItalic", type: "boolean", optional: true, description: "Italic subtitle" },
				quoteItalic: { name: "quoteItalic", type: "boolean", optional: true, description: "Italic quote" },
				addendumItalic: { name: "addendumItalic", type: "boolean", optional: true, description: "Italic addendum" },
				titleStrikethrough: { name: "titleStrikethrough", type: "boolean", optional: true, description: "Strikethrough title" },
				subtitleStrikethrough: { name: "subtitleStrikethrough", type: "boolean", optional: true, description: "Strikethrough subtitle" },
				quoteStrikethrough: { name: "quoteStrikethrough", type: "boolean", optional: true, description: "Strikethrough quote" },
				addendumStrikethrough: { name: "addendumStrikethrough", type: "boolean", optional: true, description: "Strikethrough addendum" },
				titleUnderline: { name: "titleUnderline", type: "boolean", optional: true, description: "Underline title" },
				subtitleUnderline: { name: "subtitleUnderline", type: "boolean", optional: true, description: "Underline subtitle" },
				quoteUnderline: { name: "quoteUnderline", type: "boolean", optional: true, description: "Underline quote" },
				addendumUnderline: { name: "addendumUnderline", type: "boolean", optional: true, description: "Underline addendum" },
				titleFontSize: { name: "titleFontSize", type: "number", optional: true, description: "Per-item title font size (overrides global)" },
				subtitleFontSize: { name: "subtitleFontSize", type: "number", optional: true, description: "Per-item subtitle font size (overrides global)" },
				quoteFontSize: { name: "quoteFontSize", type: "number", optional: true, description: "Per-item quote font size (overrides global)" },
				addendumFontSize: { name: "addendumFontSize", type: "number", optional: true, description: "Per-item addendum font size (overrides global)" },
			},
		},
		templateTitleSlideNumber: {
			name: "templateTitleSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the title template (null = auto-detect)",
		},
		templateContentSlideNumber: {
			name: "templateContentSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the content template (null = auto-detect)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9,
			description: "Slide number to start inserting at",
		},
		overrideTitleTextBoxKey: {
			name: "overrideTitleTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: section-title-text-box",
		},
		overrideSubtitleTextBoxKey: {
			name: "overrideSubtitleTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: section-subtitle-text-box",
		},
		overrideQuoteTextBoxKey: {
			name: "overrideQuoteTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: quote-text-box",
		},
		overrideAddendumTextBoxKey: {
			name: "overrideAddendumTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: addendum-text-box",
		},
		titleColor: {
			name: "titleColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for title text, e.g. DARK1 (default)",
		},
		subtitleColor: {
			name: "subtitleColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for subtitle text, e.g. DARK1 (default)",
		},
		quoteColor: {
			name: "quoteColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for quote text, e.g. DARK1 (default)",
		},
		addendumColor: {
			name: "addendumColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for addendum text, e.g. DARK1 (default)",
		},
		titleFontSize: {
			name: "titleFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for title text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		subtitleFontSize: {
			name: "subtitleFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for subtitle text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		quoteFontSize: {
			name: "quoteFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for quote text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		addendumFontSize: {
			name: "addendumFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for addendum text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		titleStrikethrough: {
			name: "titleStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough title text",
		},
		subtitleStrikethrough: {
			name: "subtitleStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough subtitle text",
		},
		quoteStrikethrough: {
			name: "quoteStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough quote text",
		},
		addendumStrikethrough: {
			name: "addendumStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough addendum text",
		},
		titleUnderline: {
			name: "titleUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline title text",
		},
		subtitleUnderline: {
			name: "subtitleUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline subtitle text",
		},
		quoteUnderline: {
			name: "quoteUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline quote text",
		},
		addendumUnderline: {
			name: "addendumUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline addendum text",
		},
	},
};

export const createShortQuotesSlidesSchema: FunctionSchema = {
	name: "createShortQuotesSlides",
	description: "Creates short quote slides",
	parameters: {
		shortQuoteItems: {
			name: "shortQuoteItems",
			type: "object[]",
			optional: true,
			defaultValue: undefined,
			description: "Array of short quote items with quote and addendum text",
			arrayItemSchema: {
				quote: { name: "quote", type: "string", optional: false },
				addendum: { name: "addendum", type: "string", optional: false },
				quoteColor: { name: "quoteColor", type: "string", optional: true, description: "Per-item quote color, e.g. DARK1 (overrides global)" },
				addendumColor: { name: "addendumColor", type: "string", optional: true, description: "Per-item addendum color, e.g. DARK1 (overrides global)" },
				quoteBold: { name: "quoteBold", type: "boolean", optional: true, description: "Bold quote (default: false)" },
				addendumBold: { name: "addendumBold", type: "boolean", optional: true, description: "Bold addendum (default: false)" },
				quoteItalic: { name: "quoteItalic", type: "boolean", optional: true, description: "Italic quote" },
				addendumItalic: { name: "addendumItalic", type: "boolean", optional: true, description: "Italic addendum" },
				quoteStrikethrough: { name: "quoteStrikethrough", type: "boolean", optional: true, description: "Strikethrough quote" },
				addendumStrikethrough: { name: "addendumStrikethrough", type: "boolean", optional: true, description: "Strikethrough addendum" },
				quoteUnderline: { name: "quoteUnderline", type: "boolean", optional: true, description: "Underline quote" },
				addendumUnderline: { name: "addendumUnderline", type: "boolean", optional: true, description: "Underline addendum" },
				quoteFontSize: { name: "quoteFontSize", type: "number", optional: true, description: "Per-item quote font size (overrides global)" },
				addendumFontSize: { name: "addendumFontSize", type: "number", optional: true, description: "Per-item addendum font size (overrides global)" },
			},
		},
		templateSlideNumber: {
			name: "templateSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the template (null = auto-detect)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9,
			description: "Slide number to start inserting at",
		},
		overrideQuoteTextBoxKey: {
			name: "overrideQuoteTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: quote-text-box",
		},
		overrideAddendumTextBoxKey: {
			name: "overrideAddendumTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: addendum-text-box",
		},
		quoteColor: {
			name: "quoteColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for quote text, e.g. DARK1 (default)",
		},
		addendumColor: {
			name: "addendumColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for addendum text, e.g. DARK1 (default)",
		},
		quoteFontSize: {
			name: "quoteFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for quote text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		addendumFontSize: {
			name: "addendumFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for addendum text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		quoteStrikethrough: {
			name: "quoteStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough quote text",
		},
		addendumStrikethrough: {
			name: "addendumStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough addendum text",
		},
		quoteUnderline: {
			name: "quoteUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline quote text",
		},
		addendumUnderline: {
			name: "addendumUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline addendum text",
		},
	},
};

export const setHeadersSchema: FunctionSchema = {
	name: "setHeaders",
	description: "Sets header bars on a range of slides",
	parameters: {
		templateSlideNumber: {
			name: "templateSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the header template (null = auto-detect)",
		},
		setHeaderItems: {
			name: "setHeaderItems",
			type: "object[]",
			optional: true,
			defaultValue: undefined,
			description: "Array of header section definitions",
			arrayItemSchema: {
				sectionName: { name: "sectionName", type: "string", optional: true, description: "Section name (shown in bold on the header)" },
				sectionStartSlideNumber: { name: "sectionStartSlideNumber", type: "number", optional: false },
				sectionEndSlideNumber: { name: "sectionEndSlideNumber", type: "number", optional: false },
			},
		},
		headerLength: {
			name: "headerLength",
			type: "number",
			optional: true,
			defaultValue: 3,
			description: "Number of header slots per slide",
		},
		overrideBorderKey: {
			name: "overrideBorderKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: top-bar-border-key",
		},
		overrideTopicPrefix: {
			name: "overrideTopicPrefix",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: top-bar-topic-{i}-of-{n}-text",
		},
		activeSectionColor: {
			name: "activeSectionColor",
			type: "string",
			optional: true,
			defaultValue: "DARK1",
			description: "Theme color for the active section, e.g. DARK1 (default)",
		},
		inactiveSectionColor: {
			name: "inactiveSectionColor",
			type: "string",
			optional: true,
			defaultValue: "LIGHT1",
			description: "Theme color for inactive sections, e.g. LIGHT1 (default)",
		},
		activeSectionItalic: {
			name: "activeSectionItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic for active section",
		},
		inactiveSectionItalic: {
			name: "inactiveSectionItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic for inactive sections",
		},
		activeSectionStrikethrough: {
			name: "activeSectionStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough for active section",
		},
		inactiveSectionStrikethrough: {
			name: "inactiveSectionStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough for inactive sections",
		},
		activeSectionUnderline: {
			name: "activeSectionUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline for active section",
		},
		inactiveSectionUnderline: {
			name: "inactiveSectionUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline for inactive sections",
		},
		activeSectionFontSize: {
			name: "activeSectionFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for active section in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		inactiveSectionFontSize: {
			name: "inactiveSectionFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for inactive sections in hundredths of a point (e.g. 2400 = 24 pt)",
		},
	},
};

export const replaceAllSchema: FunctionSchema = {
	name: "replaceAll",
	description: "Replaces text across slides in a range",
	parameters: {
		oldText: {
			name: "oldText",
			type: "string",
			optional: true,
			defaultValue: "",
			description: "Text to find",
		},
		newText: {
			name: "newText",
			type: "string",
			optional: true,
			defaultValue: "",
			description: "Text to replace with",
		},
		matchCase: {
			name: "matchCase",
			type: "boolean",
			optional: true,
			defaultValue: false,
			description: "Whether to match case",
		},
		lowerBoundSlideNumber: {
			name: "lowerBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 1,
			description: "Lower bound slide number (inclusive)",
		},
		upperBoundSlideNumber: {
			name: "upperBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: Infinity,
			description: "Upper bound slide number (inclusive)",
		},
	},
};

export const createHighlightVariationSlidesSchema: FunctionSchema = {
	name: "createHighlightVariationSlides",
	description: "Creates highlight variation slides from a source slide",
	parameters: {
		inputSlideNumber: {
			name: "inputSlideNumber",
			type: "number",
			optional: true,
			defaultValue: -1,
			description: "Slide number of the highlight slide to vary",
		},
		highlightColor: {
			name: "highlightColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for highlighted points, e.g. DARK1 (default)",
		},
		dimmedColor: {
			name: "dimmedColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for dimmed points, e.g. LIGHT1 (default)",
		},
		highlightBold: {
			name: "highlightBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Bold highlighted points (default: true)",
		},
		dimmedBold: {
			name: "dimmedBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Bold dimmed points (default: false)",
		},
		highlightBorderColor: {
			name: "highlightBorderColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Border color for highlighted points",
		},
		dimmedBorderColor: {
			name: "dimmedBorderColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Border color for dimmed points",
		},
		highlightItalic: {
			name: "highlightItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic highlighted points",
		},
		dimmedItalic: {
			name: "dimmedItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic dimmed points",
		},
		highlightStrikethrough: {
			name: "highlightStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough highlighted points",
		},
		dimmedStrikethrough: {
			name: "dimmedStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough dimmed points",
		},
		highlightUnderline: {
			name: "highlightUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline highlighted points",
		},
		dimmedUnderline: {
			name: "dimmedUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline dimmed points",
		},
		highlightFontSize: {
			name: "highlightFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for highlighted points in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		dimmedFontSize: {
			name: "dimmedFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for dimmed points in hundredths of a point (e.g. 2400 = 24 pt)",
		},
	},
};

export const createLongQuotesSlidesFromDocSchema: FunctionSchema = {
	name: "createLongQuotesSlidesFromDoc",
	description: "Creates long quote slides by parsing a Google Document",
	parameters: {
		inputDocumentUrl: {
			name: "inputDocumentUrl",
			type: "string",
			optional: false,
			description: "URL of the Google Document to parse",
		},
		titleAllowList: {
			name: "titleAllowList",
			type: "RegExp[]",
			optional: false,
			description: "Only include sections whose title matches these patterns",
		},
		titleBlockList: {
			name: "titleBlockList",
			type: "RegExp[]",
			optional: false,
			description: "Exclude sections whose title matches these patterns",
		},
		templateTitleSlideNumber: {
			name: "templateTitleSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the title template (null for auto-detect)",
		},
		templateContentSlideNumber: {
			name: "templateContentSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the content template (null for auto-detect)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: false,
			description: "Slide number to start inserting at",
		},
		overrideTitleTextBoxKey: {
			name: "overrideTitleTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: section-title-text-box",
		},
		overrideSubtitleTextBoxKey: {
			name: "overrideSubtitleTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: section-subtitle-text-box",
		},
		overrideQuoteTextBoxKey: {
			name: "overrideQuoteTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: quote-text-box",
		},
		overrideAddendumTextBoxKey: {
			name: "overrideAddendumTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: addendum-text-box",
		},
		titleColor: {
			name: "titleColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for title text, e.g. DARK1 (default)",
		},
		subtitleColor: {
			name: "subtitleColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for subtitle text, e.g. DARK1 (default)",
		},
		quoteColor: {
			name: "quoteColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for quote text, e.g. DARK1 (default)",
		},
		addendumColor: {
			name: "addendumColor",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Theme color for addendum text, e.g. DARK1 (default)",
		},
		titleFontSize: {
			name: "titleFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for title text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		subtitleFontSize: {
			name: "subtitleFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for subtitle text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		quoteFontSize: {
			name: "quoteFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for quote text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		addendumFontSize: {
			name: "addendumFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for addendum text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		defaultSplitMode: {
			name: "defaultSplitMode",
			type: "string",
			optional: true,
			defaultValue: "paragraph",
			description: "Default split mode for quotes: \"paragraph\", \"sentence\", \"char-count\", or \"none\"",
		},
		defaultSplitMaxChars: {
			name: "defaultSplitMaxChars",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Max chars per split when defaultSplitMode is char-count",
		},
		joinConsecutiveQuotes: {
			name: "joinConsecutiveQuotes",
			type: "boolean",
			optional: true,
			defaultValue: false,
			description: "Merge consecutive Normal paragraphs into one quote item",
		},
		requireSubtitle: {
			name: "requireSubtitle",
			type: "boolean",
			optional: true,
			defaultValue: true,
			description: "Require H2 headings as subtitles; false allows H1 > Normal directly",
		},
		subtitleAllowList: {
			name: "subtitleAllowList",
			type: "RegExp[]",
			optional: true,
			defaultValue: undefined,
			description: "Only include subtitles matching these patterns",
		},
		subtitleBlockList: {
			name: "subtitleBlockList",
			type: "RegExp[]",
			optional: true,
			defaultValue: undefined,
			description: "Exclude subtitles matching these patterns",
		},
		defaultTitleBold: {
			name: "defaultTitleBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default bold for title text (per-item overrides apply after this)",
		},
		defaultSubtitleBold: {
			name: "defaultSubtitleBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default bold for subtitle text",
		},
		defaultQuoteBold: {
			name: "defaultQuoteBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default bold for quote text",
		},
		defaultAddendumBold: {
			name: "defaultAddendumBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default bold for addendum text",
		},
		defaultTitleItalic: {
			name: "defaultTitleItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default italic for title text (per-item overrides apply after this)",
		},
		defaultSubtitleItalic: {
			name: "defaultSubtitleItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default italic for subtitle text",
		},
		defaultQuoteItalic: {
			name: "defaultQuoteItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default italic for quote text",
		},
		defaultAddendumItalic: {
			name: "defaultAddendumItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default italic for addendum text",
		},
		defaultTitleStrikethrough: {
			name: "defaultTitleStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default strikethrough for title text (per-item overrides apply after this)",
		},
		defaultSubtitleStrikethrough: {
			name: "defaultSubtitleStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default strikethrough for subtitle text",
		},
		defaultQuoteStrikethrough: {
			name: "defaultQuoteStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default strikethrough for quote text",
		},
		defaultAddendumStrikethrough: {
			name: "defaultAddendumStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default strikethrough for addendum text",
		},
		defaultTitleUnderline: {
			name: "defaultTitleUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default underline for title text (per-item overrides apply after this)",
		},
		defaultSubtitleUnderline: {
			name: "defaultSubtitleUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default underline for subtitle text",
		},
		defaultQuoteUnderline: {
			name: "defaultQuoteUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default underline for quote text",
		},
		defaultAddendumUnderline: {
			name: "defaultAddendumUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Default underline for addendum text",
		},
	},
};

export const createBulletSlideSchema: FunctionSchema = {
	name: "createBulletSlide",
	description: "Creates a slide from a title and list of bullet points",
	parameters: {
		title: {
			name: "title",
			type: "string",
			optional: false,
			description: "Title text for the bullet slide",
		},
		bullets: {
			name: "bullets",
			type: "string[]",
			optional: false,
			description: "Array of bullet point texts",
		},
		templateSlideNumber: {
			name: "templateSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the bullet slide template (null = auto-detect)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9,
			description: "Slide number to insert at",
		},
		overrideTitleTextBoxKey: {
			name: "overrideTitleTextBoxKey",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: bullet-title-text-box",
		},
		overrideBulletPrefix: {
			name: "overrideBulletPrefix",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "Default: bullet-point-{i}-text",
		},
		titleColor: {
			name: "titleColor",
			type: "string",
			optional: true,
			defaultValue: "DARK1",
			description: "Theme color for title text, e.g. DARK1 (default)",
		},
		bulletColor: {
			name: "bulletColor",
			type: "string",
			optional: true,
			defaultValue: "DARK1",
			description: "Theme color for bullet text, e.g. DARK1 (default)",
		},
		titleItalic: {
			name: "titleItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic title text",
		},
		bulletItalic: {
			name: "bulletItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic bullet text",
		},
		titleStrikethrough: {
			name: "titleStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough title text",
		},
		bulletStrikethrough: {
			name: "bulletStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough bullet text",
		},
		titleUnderline: {
			name: "titleUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline title text",
		},
		bulletUnderline: {
			name: "bulletUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline bullet text",
		},
		titleFontSize: {
			name: "titleFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for title text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		bulletFontSize: {
			name: "bulletFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for bullet text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
	},
};

export const batchSetTextStyleSchema: FunctionSchema = {
	name: "batchSetTextStyle",
	description: "Applies text style overrides (font size, italic, bold, strikethrough, underline, color, border color) to page elements matching keys",
	parameters: {
		textStyles: {
			name: "textStyles",
			type: "object[]",
			optional: false,
			description: "Array of text style overrides",
			arrayItemSchema: {
				pageElementKey: { name: "pageElementKey", type: "string", optional: false, description: "Page element key to match" },
				fontSize: { name: "fontSize", type: "number", optional: true, description: "Font size in hundredths of a point (e.g. 2400 = 24 pt)" },
				italic: { name: "italic", type: "boolean", optional: true, description: "Whether text is italic" },
				bold: { name: "bold", type: "boolean", optional: true, description: "Whether text is bold" },
				color: { name: "color", type: "string", optional: true, description: "Theme color name, e.g. DARK1, LIGHT1, ACCENT1" },
				strikethrough: { name: "strikethrough", type: "boolean", optional: true, description: "Whether text has strikethrough" },
				underline: { name: "underline", type: "boolean", optional: true, description: "Whether text has underline" },
				borderColor: { name: "borderColor", type: "string", optional: true, description: "Theme color name for border, e.g. DARK1" },
			},
		},
		lowerBoundSlideNumber: {
			name: "lowerBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 1,
			description: "Lower bound slide number (inclusive)",
		},
		upperBoundSlideNumber: {
			name: "upperBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9999,
			description: "Upper bound slide number (inclusive)",
		},
	},
};

export const duplicateSlideRangeSchema: FunctionSchema = {
	name: "duplicateSlideRange",
	description: "Duplicates a range of slides and inserts the copies at a specified position",
	parameters: {
		lowerBoundSlideNumber: {
			name: "lowerBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 1,
			description: "First slide number to duplicate (inclusive)",
		},
		upperBoundSlideNumber: {
			name: "upperBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9999,
			description: "Last slide number to duplicate (inclusive)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: false,
			description: "Slide number where the copies should be inserted",
		},
		linkingMode: {
			name: "linkingMode",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "SlideLinkingMode: LINKED to create linked copies that stay in sync, NOT_LINKED for independent copies (default)",
		},
	},
};

export const createSummarySlideSchema: FunctionSchema = {
	name: "createSummarySlide",
	description: "Creates a summary / table-of-contents slide from slide titles in a range",
	parameters: {
		lowerBoundSlideNumber: {
			name: "lowerBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 1,
			description: "First slide number to include (inclusive)",
		},
		upperBoundSlideNumber: {
			name: "upperBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9999,
			description: "Last slide number to include (inclusive)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: false,
			description: "Slide number where the summary should be inserted",
		},
		templateSlideNumber: {
			name: "templateSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number to use as template (auto-detected if null)",
		},
		summaryTitle: {
			name: "summaryTitle",
			type: "string",
			optional: true,
			defaultValue: "Summary",
			description: "Title text for the summary slide",
		},
		titleColor: {
			name: "titleColor",
			type: "string",
			optional: true,
			defaultValue: "DARK1",
			description: "Theme color for title text, e.g. DARK1 (default)",
		},
		itemColor: {
			name: "itemColor",
			type: "string",
			optional: true,
			defaultValue: "DARK1",
			description: "Theme color for item text, e.g. DARK1 (default)",
		},
		titleBold: {
			name: "titleBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Bold title text",
		},
		itemBold: {
			name: "itemBold",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Bold item text",
		},
		titleItalic: {
			name: "titleItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic title text",
		},
		itemItalic: {
			name: "itemItalic",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Italic item text",
		},
		titleStrikethrough: {
			name: "titleStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough title text",
		},
		itemStrikethrough: {
			name: "itemStrikethrough",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Strikethrough item text",
		},
		titleUnderline: {
			name: "titleUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline title text",
		},
		itemUnderline: {
			name: "itemUnderline",
			type: "boolean",
			optional: true,
			defaultValue: undefined,
			description: "Underline item text",
		},
		titleFontSize: {
			name: "titleFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for title text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
		itemFontSize: {
			name: "itemFontSize",
			type: "number",
			optional: true,
			defaultValue: undefined,
			description: "Font size for item text in hundredths of a point (e.g. 2400 = 24 pt)",
		},
	},
};

export const applyBackgroundColorSchema: FunctionSchema = {
	name: "applyBackgroundColor",
	description: "Sets the background color for a range of slides",
	parameters: {
		color: {
			name: "color",
			type: "string",
			optional: false,
			description: "Theme color type to apply as background (e.g. DARK1, LIGHT1, ACCENT1)",
		},
		lowerBoundSlideNumber: {
			name: "lowerBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 1,
			description: "Lower bound slide number (inclusive)",
		},
		upperBoundSlideNumber: {
			name: "upperBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9999,
			description: "Upper bound slide number (inclusive)",
		},
	},
};

export const moveSlidesSchema: FunctionSchema = {
	name: "moveSlides",
	description: "Moves a range of slides to a new position",
	parameters: {
		fromSlideNumber: {
			name: "fromSlideNumber",
			type: "number",
			optional: false,
			description: "First slide number to move (inclusive)",
		},
		toSlideNumber: {
			name: "toSlideNumber",
			type: "number",
			optional: false,
			description: "Last slide number to move (inclusive)",
		},
		targetSlideNumber: {
			name: "targetSlideNumber",
			type: "number",
			optional: false,
			description: "Slide number where the range should be inserted before",
		},
		linkingMode: {
			name: "linkingMode",
			type: "string",
			optional: true,
			defaultValue: undefined,
			description: "SlideLinkingMode: LINKED to create linked copies that stay in sync, NOT_LINKED for independent copies (default)",
		},
	},
};

export const batchReplaceTextSchema: FunctionSchema = {
	name: "batchReplaceText",
	description: "Performs multiple text replacements across slides in a range",
	parameters: {
		replacements: {
			name: "replacements",
			type: "object[]",
			optional: false,
			description: "Array of oldText/newText replacement pairs",
			arrayItemSchema: {
				oldText: { name: "oldText", type: "string", optional: false },
				newText: { name: "newText", type: "string", optional: false },
			},
		},
		matchCase: {
			name: "matchCase",
			type: "boolean",
			optional: true,
			defaultValue: false,
			description: "Whether to match case when replacing",
		},
		lowerBoundSlideNumber: {
			name: "lowerBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 1,
			description: "Lower bound slide number (inclusive)",
		},
		upperBoundSlideNumber: {
			name: "upperBoundSlideNumber",
			type: "number",
			optional: true,
			defaultValue: 9999,
			description: "Upper bound slide number (inclusive)",
		},
	},
};

export const createVerseSlidesSchema: FunctionSchema = {
	name: "createVerseSlides",
	description: "Creates short quote slides from Bible verse references, fetched from jsonbible.com",
	parameters: {
		verseItemInputs: {
			name: "verseItemInputs",
			type: "string[]",
			optional: false,
			defaultValue: undefined,
			description: "Verse references, e.g. \"Psalms 42:5 niv\" or a range \"Psalms 42:5-6 niv\"",
		},
		templateSlideNumber: {
			name: "templateSlideNumber",
			type: "number",
			optional: true,
			defaultValue: null,
			description: "Slide number of the quote template (null for auto-detect)",
		},
		insertionSlideNumber: {
			name: "insertionSlideNumber",
			type: "number",
			optional: false,
			defaultValue: 9,
			description: "Slide number to start inserting at",
		},
	},
};

export const functionSchemas: Record<string, FunctionSchema> = {
	createLongQuotesSlides: createLongQuotesSlidesSchema,
	createShortQuotesSlides: createShortQuotesSlidesSchema,
	setHeaders: setHeadersSchema,
	replaceAll: replaceAllSchema,
	createHighlightVariationSlides: createHighlightVariationSlidesSchema,
	createLongQuotesSlidesFromDoc: createLongQuotesSlidesFromDocSchema,
	createBulletSlide: createBulletSlideSchema,
	createSummarySlide: createSummarySlideSchema,
	batchSetTextStyle: batchSetTextStyleSchema,
	duplicateSlideRange: duplicateSlideRangeSchema,
	moveSlides: moveSlidesSchema,
	applyBackgroundColor: applyBackgroundColorSchema,
	batchReplaceText: batchReplaceTextSchema,
	createVerseSlides: createVerseSlidesSchema,
};

export const allFunctionNames: string[] = Object.keys(functionSchemas);
